### ISSUE TITLE
Changing Address at the checkout - LOADING 

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#23]
Hi , @wildfirecreative @supremesupports 
This is still happening after you have fixed the address , 

When i try to apply my voucher code at the check out 
I have multiple addresses , for international, australia and others to test shipping
I wanted to change MY ADDRESS to australia and the site started LOADING 
It wouldn't process further

Can you have a look pls

Thanks
JOsh 
![screen shot 2015-08-23 at 8 55 15 pm](https://cloud.githubusercontent.com/assets/9522928/9427926/a75c5b4c-49d8-11e5-8638-f36760968db7.png)

**Comment by Stellyclothing** [comment]
It's happening again ,

when i randomly deduct an item at the check out 
so assuming it's the delivering method , thats the problem 


![screen shot 2015-08-25 at 12 31 41 pm](https://cloud.githubusercontent.com/assets/9522928/9457351/f81b0a0e-4b24-11e5-8db2-b2863dee1526.png)

**Comment by supremesupports** [comment]
This issue is fixed. Please check now.

**Comment by Stellyclothing** [comment]
Hey @supremesupports @wildfirecreative 
I See that you changed from 1 page checkout to 3 pages check out 

we are still having problem 

Error messages just came up when i try to change 
![screen shot 2015-08-25 at 3 45 44 pm](https://cloud.githubusercontent.com/assets/9522928/9459545/24feb4ce-4b40-11e5-971f-73e70af5939f.png)

**Comment by supremesupports** [comment]
Hi,
Can you please check this now? Its working.

Thanks.

**Comment by Stellyclothing** [comment]
Hey @supremesupports  it works fine

 but why 5 steps check out 
We have 1 page check out on our current site 
I just tried to change to page check out on my CMS and i get a blank page instead   
![screen shot 2015-08-25 at 6 59 17 pm](https://cloud.githubusercontent.com/assets/9522928/9462647/8d07d2de-4b5a-11e5-8797-5c7c16ee3122.png)

Please Let me know 

Thanks 
josh

**Comment by supremesupports** [comment]
Hi Josh,

One page checkout is available in Prestashop 1.6 but you can't use it with your current theme. If you want to use this option then you will need to use it with a updated theme which is compatible with Prestahop 1.6. Stelly theme is a custom coded theme which is more compatible with prestahop 1.4 & it does not support auto upgrade. Hope you understood this situation.

Thanks!

**Comment by Stellyclothing** [comment]
Hi @supremesupports @wildfirecreative 

Can we customise the current check out theme to be compatible with PS 1.6?

Thanks
Phong

**Comment by supremesupports** [comment]
Hi Phong,

Yes we can, if we spend a good amount of time in it because whole part needs to be custom coded.

Thanks.

**Comment by Stellyclothing** [comment]
Hi 

I understand. 

Thanks
Phong
