### ISSUE TITLE
Inventory Issues

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#5]
Hi

Category page shown available inventory on each product. However, when go into product itself, the inventories are not shown & out of stock. Can you please correct this issue?

Thanks
Phong

![frontproduct](https://cloud.githubusercontent.com/assets/9522928/9241537/43b0fe40-41b8-11e5-9e91-65bc21142fe1.PNG)
![product details](https://cloud.githubusercontent.com/assets/9522928/9241536/43a96b3a-41b8-11e5-8795-069b69ec5a2a.PNG)

**Comment by supremesupports** [comment]
Hi Phong, 
We are totally aware of this issue & we are working on it. After upgrading prestashop to its new version, stock management is not working the way it should be. We are manually working on Database to make things right.

Thanks!

**Comment by supremesupports** [comment]
This issue is solved.

**Comment by Stellyclothing** [comment]
Hi

There are still issues with these two products. Please see the attachments below for details. 

![product1 2](https://cloud.githubusercontent.com/assets/9522928/9293141/e54ef454-4461-11e5-963b-69baae88bb30.PNG)
![product1](https://cloud.githubusercontent.com/assets/9522928/9293142/e5500eca-4461-11e5-8aa8-e31ec38e3853.PNG)
![product1 1](https://cloud.githubusercontent.com/assets/9522928/9293146/268e14fe-4462-11e5-8405-24e2bdd204d0.PNG)

**Comment by supremesupports** [comment]
We are working on this issue. This issue is related to #16, #10.

**Comment by supremesupports** [comment]
This issue is fixed.

**Comment by Stellyclothing** [comment]
Hi

This issue is not fixed yet. Please see reference product 123456 for details

Thanks
Phong

**Comment by supremesupports** [comment]
Please check now. This issue is fixed.

**Comment by Stellyclothing** [comment]
Hi supremesupports.

Thank you. It is working now.

Thanks
Phong
