### ISSUE TITLE
FRONT END - ALL Products NEW & OLD all have the same descriptions  , all have the same prices $0

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/AWS-NEW-WEBSITE-TEST#58]
HI @wildfirecreative @supremesupports 
Can someone get on this fast because all of our products decriptions & Prices are wrong on the current live site

![screen shot 2015-09-09 at 11 08 47 am](https://cloud.githubusercontent.com/assets/9522928/9751104/f083f4a2-56e3-11e5-9b1d-7f6b373dc89c.png)
![screen shot 2015-09-09 at 11 08 03 am](https://cloud.githubusercontent.com/assets/9522928/9751103/f083416a-56e3-11e5-901b-2c9440c12e6c.png)

**Comment by supremesupports** [comment]
Hi,

Product price & description issues has been fixed.

Thanks.

**Comment by Stellyclothing** [comment]
Hey @supremesupports 
Some product even when we have the price on the CMS , it still listed as $0 , its still happening now 
![screen shot 2015-09-09 at 10 39 53 pm](https://cloud.githubusercontent.com/assets/9522928/9761887/cb2c9d94-5742-11e5-98ef-334260f2a545.png)

Can you please check

**Comment by supremesupports** [comment]
Hi,

Just now i checked & i found this product is not enabled. However, i saw the product preview where i found the product price is $55 rather than $0.

Can you please check back now and let us know if you are still encountering this issue.

Thanks.

**Comment by Stellyclothing** [comment]
@supremesupports 
I will look over one more time today 

Thank you
Josh

**Comment by supremesupports** [comment]
Hi Josh,

Please check & let us know. If you found any issue then send us some product ID's so that we can check easily.

Thanks

**Comment by Stellyclothing** [comment]
Hey @supremesupports 
It's happening still
Please check for me 

Thanks
Josh

**Comment by supremesupports** [comment]
Hi Josh,

Refer to your screenshot, here is what i see for the first product:

![zero-price-1](https://cloud.githubusercontent.com/assets/12905649/9868789/bc382d52-5b9e-11e5-87bf-4b522bcf3fda.PNG)

![zero-price-2](https://cloud.githubusercontent.com/assets/12905649/9868791/c3a29a00-5b9e-11e5-9260-8b5e06efb501.PNG)

Your 2nd product is disabled so i cant check that in front-end.

Can you please clear cache & check again?

Thanks.

**Comment by Stellyclothing** [comment]
Hey @supremesupports 
I'm 100% sure theres a problem , its happening agin this morning and you don't expect customers to go and empty caches everytime. This shouldn't happen so often . 
Can you have a look for me again , may be this is caching problem ?????


Thanks

**Comment by Stellyclothing** [comment]
hey @supremesupports @wildfirecreative 
I have empty my cache and try to work with different browser , so may be have a look with Safari also 
and chrome & firefox & Explore 
It's happening again today 

There are two things that we found - products are still display $0.00 with some products for some reason , not all 

In this second image , you can see even though they are the same products, same code , same reference , but when you guys upload over to the new CMS, they are two different images . 
![screen shot 2015-09-16 at 1 32 44 pm](https://cloud.githubusercontent.com/assets/9522928/9895813/3d1270d0-5c77-11e5-956d-7be064a02dea.png)

This product thing needs to be fixed urgent
Thanks
Josh

**Comment by supremesupports** [comment]
Hi,

We've debugged this issue. Whatever you are seeing in front-end is the actual Image of the product. But there are some mismatch on small images in back-end. This is happened because image has been altered for same image  ID. We are working on it.

Thanks.

**Comment by Stellyclothing** [comment]
Hey @supremesupports 
We listed three problems with this 
What about the other two ? 

Thanks
Josh

**Comment by supremesupports** [comment]
Hi,

You have given an screenshot where product (ID: 18567) is not listed in front-end so I can't check it. Besides, our current login **@arazee** have no permission to access back-end so I also can't check this on back-end either. Normally I went through category listing page & I don't see any issue regarding with price $0. However, we don't expect customer to clear there browser cache. What we can suggest is, every changes you made in back-end please consider to go to **Advanced Parameter** >> **Performance** & press **Clear Cache** button from top right. Then check if there is any impact on front-end regarding with price issue.

Problem 2 & Problem 3 are same. We are working on this issue. Basically image re-generation will take some time.

Thanks.

**Comment by Stellyclothing** [comment]
Hey @supremesupports 
You do have permission to access back end to parameter , modules and catelouge & products 

Okay thanks , let me know when those issues are done

**Comment by Stellyclothing** [comment]
@supremesupports 
You can go to NEW TREATS AND GO TO THAT SAME PRODUCT & ACTIVATELUNA ECLIPSE TO TEST IT FOR YOURSELF .

Thanks
Josh

**Comment by Stellyclothing** [comment]
Hey @supremesupports 

Back to my $0 issue 

I put these two products in a seperate url for Testing
in here you will see these 2 products with $0 even thought on the backend it has prices

http://stelly.com.au/185-testing
Lets have a look and let me know 

Thank you
Josh

**Comment by supremesupports** [comment]
Hi Josh,

I've tested this part & it quite complicated that why ONLY those 2 products are showing $0 price. Please check this URL: http://stelly.com.au/185-testing & as well as following scenario: 

1. I've created a new product (ID: 18701) under same category which has no problem of showing price.

2. I've duplicate one of your product (ID: 18702) which is also showing price.

3. I've created new product (ID: 18704) with initial price $20. It was showing in front-end. Then I change price to $21.55 which is appearing as well. There is no $0 price issue I've faced.

Can you please also check this & see what's happening to your end? One more question, have you manually created those $0 price product from back-end or its generated/imported from any CSV or something?

Thanks.

**Comment by Stellyclothing** [comment]
Hey @supremesupports @wildfirecreative 
Im sure i have replied to your comment on here, 
Dont know why its not showing up

 http://stelly.com.au/185-testing  
Under testing , we have 3 kinds of problem

1.$0
2.Back end images on CMS & front end images are not the same 
3.Or just Front End images are incorrect  ( not the same as the second one )
How are we doing with problem 2 & 3 ? 

We upload every single product manually on our back end without going through the CSV file
Here is our usual process:

single product is created 
Then add the quantity
Then add the pricing & enable online

I have tried to duplicate the $0 product , it works  but it happens to many of our products so that method will not work every time, and it will affect on how we merchandise on our website.

As you can see this attachment i have on our website today under new treats - Page 2 
Cache has been cleared , so when i click into the product, full sizes but on category page : 

![screen shot 2015-09-23 at 11 04 16 am](https://cloud.githubusercontent.com/assets/9522928/10035927/3b002c26-61e3-11e5-8c24-410963d712e3.png) these products are not in Testing page

This is a major major issue

Thanks 
Josh

**Comment by Stellyclothing** [comment]
@wildfirecreative @supremesupports 
Can you let me now what are you up to ?
it has been 2 weeks already

Thanks

**Comment by supremesupports** [comment]
Hi,
We missed your last post of 7 days ago. We are checking the issues and we will send you update in the next few hours. 

We found that these problems are happening when any filter option or pagination is clicked. 

we need a real example with screenshot of "Back end images on CMS & front end images are not the same "

Thanks

**Comment by supremesupports** [comment]
Hi,
These issues are fixed. Please check now.
Thanks

**Comment by Stellyclothing** [comment]
Hey @supremesupports @wildfirecreative 
I see the $0 is now fixed, but i will continue checking
I have posted the example of back and front end images are not the same, Just scroll up 
Otherwise check out these images 
There are more , but here are the two we found 

Everything we are not sure, we will put under http://stelly.com.au/185-testing

http://stelly.com.au/printed-paradise/18359-lace-up-turtle-neck-crop-top-grey.html
http://stelly.com.au/printed-paradise/18442-lace-pencil-skirt-red-reshoot.html
![screen shot 2015-10-01 at 1 14 26 pm](https://cloud.githubusercontent.com/assets/9522928/10212092/f62a6222-683d-11e5-841e-2f17cbbb479f.png)

**Comment by Stellyclothing** [comment]
Hey @supremesupports @wildfirecreative 

Andi stretch skater Skirt..
![screen shot 2015-10-01 at 1 22 10 pm](https://cloud.githubusercontent.com/assets/9522928/10212199/06d35920-683f-11e5-8862-a47f28d3f897.png)

its still happening now as i activated one of the product that had $0 yesterday
SO it's not yet completely fixed 

Thanks
![screen shot 2015-10-01 at 1 23 28 pm](https://cloud.githubusercontent.com/assets/9522928/10212210/29eafe72-683f-11e5-973c-fdc15c3ac281.png)
